1. Small arrays

In [ ]:
import numpy as np, random
from timeit import timeit

def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

Z1 = random.sample(range(1000), 100)
Z2 = random.sample(range(1000), 100)

python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=1000)
numpy_time = timeit("add_numpy(np.array(Z1), np.array(Z2))", globals=globals(), number=10000)

print(f"Pure Python addition: {python_time:.4f} s per loop")
print(f"NumPy addition: {numpy_time:.4f} s per loop")


Pure Python addition: 0.0314 s per loop
NumPy addition: 0.2156 s per loop


2. Large arrays

In [ ]:
import numpy as np, random
from timeit import timeit

def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

size = 100_000
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)

python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

print(f"Pure Python addition: {python_time:.6f} s per loop")
print(f"NumPy addition: {numpy_time:.6f} s per loop")


Pure Python addition: 2.968953 s per loop
NumPy addition: 0.008408 s per loop


3. Zeros array and shape

In [ ]:
zeros_arr = np.zeros((2, 3))
print("Array:\n", zeros_arr)
print("Shape:", zeros_arr.shape, "ndim:", zeros_arr.ndim, "dtype:", zeros_arr.dtype)


Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3) ndim: 2 dtype: float64


4. Zero-, one-, and two-dimensional arrays

In [ ]:
zero_dim = np.array(5)
one_dim = np.array([1, 2, 3])
two_dim = np.array([[1, 2], [3, 4]])

for arr in [zero_dim, one_dim, two_dim]:
    print(arr, "\nndim:", arr.ndim, "dtype:", arr.dtype, "shape:", arr.shape, "\n")


5 
ndim: 0 dtype: int64 shape: () 

[1 2 3] 
ndim: 1 dtype: int64 shape: (3,) 

[[1 2]
 [3 4]] 
ndim: 2 dtype: int64 shape: (2, 2) 



5. Shapes across 0D, 1D, 2D, 3D

In [ ]:
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D array shape:", arr.shape)


0D array shape: ()
1D array shape: (5,)
2D array shape: (2, 3)
3D array shape: (2, 2, 2)


6. Reshape without changing data

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
reshaped = arr.reshape(3, 2)            
print("Original:", arr.shape, "Reshaped:", reshaped.shape)


Original: (2, 3) Reshaped: (3, 2)


7. arange basics

In [ ]:
print(np.arange(1, 10))     
print(np.arange(10.4))         
print(np.arange(0.5, 10.4, 0.8))


[1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


8. linspace basics

In [ ]:
print(np.linspace(1, 10))             
print(np.linspace(1, 10, 7))          
print(np.linspace(1, 10, 7, endpoint=False)) 


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


9. ones, zeros, empty, identity

In [ ]:
ones = np.ones((2, 3))
zeros = np.zeros((3, 2))
empty = np.empty((2, 2))
eye = np.eye(3)
for name, arr in [("ones", ones), ("zeros", zeros), ("empty", empty), ("eye", eye)]:
    print(name, "shape:", arr.shape, "\n", arr, "\n")


ones shape: (2, 3) 
 [[1. 1. 1.]
 [1. 1. 1.]] 

zeros shape: (3, 2) 
 [[0. 0.]
 [0. 0.]
 [0. 0.]] 

empty shape: (2, 2) 
 [[0. 0.]
 [0. 0.]] 

eye shape: (3, 3) 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



10. From list, tuple, nested list

In [ ]:
arr_list = np.array([1, 2, 3])
arr_tuple = np.array((4, 5, 6))
arr_nested = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_list, arr_tuple, arr_nested, sep="\n")


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


11. Create arrays with the same shape

In [ ]:
base = np.array([[1, 2, 3], [4, 5, 6]])  
zeros = np.zeros(base.shape)
ones = np.ones(base.shape)
empty = np.empty(base.shape)
print("base:\n", base, "\nzeros:\n", zeros, "\nones:\n", ones, "\nempty:\n", empty)


base:
 [[1 2 3]
 [4 5 6]] 
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]] 
ones:
 [[1. 1. 1.]
 [1. 1. 1.]] 
empty:
 [[1. 1. 1.]
 [1. 1. 1.]]


12. Element-wise arithmetic, copy, slicing

In [ ]:
arr = np.array([1, 2, 3])
doubled = arr * 2
copied = np.copy(arr)
sliced = arr[1:2] 
print("doubled:", doubled, "copied:", copied, "sliced:", sliced)


doubled: [2 4 6] copied: [1 2 3] sliced: [2]


13. Horizontal and vertical stack; column_stack

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

h = np.hstack((a, b))  
v = np.vstack((a, b))  
c = np.column_stack((a[0], b[0]))
print("hstack:\n", h, "\n\nvstack:\n", v, "\n\ncolumn_stack:\n", c)


hstack:
 [[1 2 5 6]
 [3 4 7 8]] 

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

column_stack:
 [[1 5]
 [2 6]]


14. Concatenate along axis=0 and axis=1

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concat0 = np.concatenate((arr1, arr2), axis=0)  
concat1 = np.concatenate((arr1, arr2), axis=1) 
print("axis=0:\n", concat0, "\n\naxis=1:\n", concat1)


axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


15. Concatenate shape mismatch error (intentional)

In [ ]:
try:
    np.ones((3, 3)) + np.ones((2, 2))
except ValueError as e:
    print("Expected broadcasting error:", e)


Expected broadcasting error: operands could not be broadcast together with shapes (3,3) (2,2) 


16. 1D slicing: basic, step, negatives

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
print("basic:", arr[1:4])            
print("step:", arr[1:5:2])         
print("negatives:", arr[-3:])        
print("entire:", arr[:])      


basic: [1 2 3]
step: [1 3]
negatives: [3 4 5]
entire: [0 1 2 3 4 5]


17. 2D slicing: rows and columns

In [ ]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
print("block:", arr[1:3, 0:2])       
print("rows step:", arr[::2, :])       
print("cols step:", arr[:, 1::2])       
print("last rows/cols:", arr[-2:, -2:])


block: [[3 4]
 [6 7]]
rows step: [[0 1 2]
 [6 7 8]]
cols step: [[1]
 [4]
 [7]]
last rows/cols: [[4 5]
 [7 8]]


18. 3D slicing: depth, rows, cols

In [ ]:
arr = np.array([
    [[0, 1], [2, 3]],
    [[4, 5], [6, 7]],
    [[8, 9], [10, 11]]
])
print("basic:", arr[1:2, 0:2, 1:2]) 
print("stepped:", arr[::2, ::2, 1::2])


basic: [[[5]
  [7]]]
stepped: [[[1]]

 [[9]]]


19. Elementary ufuncs

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("add:", np.add(a, b))
print("sub:", np.subtract(a, b))
print("div:", np.divide(a, b))
print("mul:", np.multiply(a, b))
print("pow:", np.power(a, b))
print("exp:", np.exp(a))


add: [5 7 9]
sub: [-3 -3 -3]
div: [0.25 0.4  0.5 ]
mul: [ 4 10 18]
pow: [  1  32 729]
exp: [ 2.71828183  7.3890561  20.08553692]


20. Aggregations and args

In [ ]:
x = np.array([3, 1, 4, 1, 5, 9])
print("mean:", np.mean(x))
print("std:", np.std(x))
print("var:", np.var(x))
print("min/max:", np.min(x), np.max(x))
print("argmin/argmax:", np.argmin(x), np.argmax(x))
print("argsort:", np.argsort(x))
print("array_equal:", np.array_equal(x, x.copy()))


mean: 3.8333333333333335
std: 2.733536577809454
var: 7.472222222222221
min/max: 1 9
argmin/argmax: 1 5
argsort: [1 3 0 2 4 5]
array_equal: True


21. Scalar + vector

In [ ]:
arr = np.array([1, 2, 3])
print(arr + 1)


[2 3 4]


22. Vector + matrix row-wise

In [ ]:
arr1 = np.array([[4, 5, 6],
                 [7, 8, 9]])         
arr2 = np.array([1, 2, 3])        
print(arr1 + arr2)                 

[[ 5  7  9]
 [ 8 10 12]]


23. dot, @, matmul

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])          
B = np.array([[7, 8], [9, 10], [11, 12]])     
print("dot:\n", np.dot(A, B))
print("@:\n", A @ B)
print("matmul:\n", np.matmul(A, B))


dot:
 [[ 58  64]
 [139 154]]
@:
 [[ 58  64]
 [139 154]]
matmul:
 [[ 58  64]
 [139 154]]


24. Inverse and determinant

In [ ]:
A = np.array([[1, 2], [3, 4]])
print("inverse:\n", np.linalg.inv(A))
print("determinant:", np.linalg.det(A))


inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant: -2.0000000000000004


25. norms

In [ ]:
A = np.array([[1, 2], [3, 4]])
print("Frobenius:", np.linalg.norm(A, 'fro'))
print("Euclidean:", np.linalg.norm(A))


Frobenius: 5.477225575051661
Euclidean: 5.477225575051661


26. Solve linear system Ax = B

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
x = np.linalg.solve(A, B)
print("solution x:", x)


solution x: [-4.   4.5]
